// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filters.proto

package chremoas_roles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FilterList struct {
	FilterList []*Filter `protobuf:"bytes,1,rep,name=FilterList" json:"FilterList,omitempty"`
}

func (m *FilterList) Reset()                    { *m = FilterList{} }
func (m *FilterList) String() string            { return proto.CompactTextString(m) }
func (*FilterList) ProtoMessage()               {}
func (*FilterList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *FilterList) GetFilterList() []*Filter {
	if m != nil {
		return m.FilterList
	}
	return nil
}

type Filter struct {
	Name        string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Filter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MemberInfo struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	List string `protobuf:"bytes,2,opt,name=List" json:"List,omitempty"`
}

func (m *MemberInfo) Reset()                    { *m = MemberInfo{} }
func (m *MemberInfo) String() string            { return proto.CompactTextString(m) }
func (*MemberInfo) ProtoMessage()               {}
func (*MemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *MemberInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberInfo) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

type MemberInfoList struct {
	Members []*MemberInfo `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
}

func (m *MemberInfoList) Reset()                    { *m = MemberInfoList{} }
func (m *MemberInfoList) String() string            { return proto.CompactTextString(m) }
func (*MemberInfoList) ProtoMessage()               {}
func (*MemberInfoList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MemberInfoList) GetMembers() []*MemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*FilterList)(nil), "chremoas.roles.FilterList")
	proto.RegisterType((*Filter)(nil), "chremoas.roles.Filter")
	proto.RegisterType((*MemberInfo)(nil), "chremoas.roles.MemberInfo")
	proto.RegisterType((*MemberInfoList)(nil), "chremoas.roles.MemberInfoList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Filters service

type FiltersClient interface {
	GetLists(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*FilterList, error)
	AddList(ctx context.Context, in *FilterList, opts ...client.CallOption) (*NilMessage, error)
	RemoveList(ctx context.Context, in *FilterList, opts ...client.CallOption) (*NilMessage, error)
	GetMembers(ctx context.Context, in *FilterList, opts ...client.CallOption) (*MemberInfoList, error)
	AddMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error)
	RemoveMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error)
}

type filtersClient struct {
	c           client.Client
	serviceName string
}

func NewFiltersClient(serviceName string, c client.Client) FiltersClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.roles"
	}
	return &filtersClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *filtersClient) GetLists(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*FilterList, error) {
	req := c.c.NewRequest(c.serviceName, "Filters.GetLists", in)
	out := new(FilterList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filtersClient) AddList(ctx context.Context, in *FilterList, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Filters.AddList", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filtersClient) RemoveList(ctx context.Context, in *FilterList, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Filters.RemoveList", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filtersClient) GetMembers(ctx context.Context, in *FilterList, opts ...client.CallOption) (*MemberInfoList, error) {
	req := c.c.NewRequest(c.serviceName, "Filters.GetMembers", in)
	out := new(MemberInfoList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filtersClient) AddMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Filters.AddMember", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filtersClient) RemoveMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Filters.RemoveMember", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Filters service

type FiltersHandler interface {
	GetLists(context.Context, *NilMessage, *FilterList) error
	AddList(context.Context, *FilterList, *NilMessage) error
	RemoveList(context.Context, *FilterList, *NilMessage) error
	GetMembers(context.Context, *FilterList, *MemberInfoList) error
	AddMember(context.Context, *MemberInfo, *NilMessage) error
	RemoveMember(context.Context, *MemberInfo, *NilMessage) error
}

func RegisterFiltersHandler(s server.Server, hdlr FiltersHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Filters{hdlr}, opts...))
}

type Filters struct {
	FiltersHandler
}

func (h *Filters) GetLists(ctx context.Context, in *NilMessage, out *FilterList) error {
	return h.FiltersHandler.GetLists(ctx, in, out)
}

func (h *Filters) AddList(ctx context.Context, in *FilterList, out *NilMessage) error {
	return h.FiltersHandler.AddList(ctx, in, out)
}

func (h *Filters) RemoveList(ctx context.Context, in *FilterList, out *NilMessage) error {
	return h.FiltersHandler.RemoveList(ctx, in, out)
}

func (h *Filters) GetMembers(ctx context.Context, in *FilterList, out *MemberInfoList) error {
	return h.FiltersHandler.GetMembers(ctx, in, out)
}

func (h *Filters) AddMember(ctx context.Context, in *MemberInfo, out *NilMessage) error {
	return h.FiltersHandler.AddMember(ctx, in, out)
}

func (h *Filters) RemoveMember(ctx context.Context, in *MemberInfo, out *NilMessage) error {
	return h.FiltersHandler.RemoveMember(ctx, in, out)
}

func init() { proto.RegisterFile("filters.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xa9, 0x10, 0x2a, 0x03, 0x72, 0x98, 0x83, 0x69, 0x7a, 0x30, 0x4d, 0x4f, 0x9c, 0x7a,
	0x40, 0xe2, 0xd1, 0x84, 0x58, 0x8b, 0x1a, 0xe1, 0xd0, 0x37, 0x28, 0xed, 0xa0, 0x4d, 0xba, 0x5d,
	0xb2, 0xb3, 0xf1, 0xdd, 0x7c, 0x3b, 0xe3, 0x6e, 0x0d, 0x55, 0xb1, 0x1e, 0xb8, 0xed, 0xcc, 0xfc,
	0xff, 0xdf, 0x6f, 0x26, 0x85, 0x8b, 0x5d, 0x59, 0x69, 0x52, 0x1c, 0xed, 0x95, 0xd4, 0x12, 0xa7,
	0xf9, 0xab, 0x22, 0x21, 0x33, 0x8e, 0x94, 0xac, 0x88, 0xfd, 0x49, 0x2e, 0x85, 0x90, 0xb5, 0x9d,
	0x86, 0x31, 0x40, 0x62, 0xe4, 0xcf, 0x25, 0x6b, 0xbc, 0x69, 0x57, 0x9e, 0x13, 0xf4, 0x67, 0xe3,
	0xf9, 0x65, 0xf4, 0x3d, 0x20, 0xb2, 0x8a, 0xb4, 0xa5, 0x0c, 0x6f, 0x61, 0x68, 0x2b, 0x44, 0x18,
	0x6c, 0x32, 0x41, 0x9e, 0x13, 0x38, 0xb3, 0x51, 0x6a, 0xde, 0x18, 0xc0, 0x38, 0x26, 0xce, 0x55,
	0xb9, 0xd7, 0xa5, 0xac, 0xbd, 0x33, 0x33, 0x6a, 0xb7, 0xc2, 0x05, 0xc0, 0x9a, 0xc4, 0x96, 0xd4,
	0x63, 0xbd, 0x93, 0x47, 0x33, 0x10, 0x06, 0x86, 0xc9, 0x9a, 0xcd, 0x3b, 0x4c, 0x60, 0x7a, 0x70,
	0x19, 0xfe, 0x05, 0xb8, 0xb6, 0xc3, 0x0d, 0xbc, 0xff, 0x13, 0xfe, 0x60, 0x48, 0xbf, 0xa4, 0xf3,
	0xf7, 0x3e, 0xb8, 0x16, 0x9f, 0x31, 0x86, 0xf3, 0x15, 0xe9, 0xcf, 0x30, 0xc6, 0x5f, 0xe6, 0x4d,
	0x59, 0xad, 0x89, 0x39, 0x7b, 0x21, 0xdf, 0x3f, 0x7e, 0x15, 0xc3, 0xd5, 0xc3, 0x3b, 0x70, 0x97,
	0x45, 0x61, 0x90, 0x3a, 0x84, 0x7e, 0xc7, 0x07, 0xc2, 0x1e, 0x26, 0x00, 0x29, 0x09, 0xf9, 0x46,
	0x27, 0xe6, 0x3c, 0x01, 0xac, 0x48, 0x37, 0xcb, 0x76, 0xe6, 0x5c, 0xfd, 0x7d, 0xad, 0x66, 0xb1,
	0x7b, 0x18, 0x2d, 0x8b, 0xc2, 0xb6, 0xb1, 0xe3, 0xb8, 0xff, 0x20, 0x3d, 0xc0, 0xc4, 0xae, 0x76,
	0x6a, 0xd2, 0x76, 0x68, 0x7e, 0xe3, 0xeb, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x77, 0x6d,
	0x94, 0xf5, 0x02, 0x00, 0x00,
}
