// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memberLists.proto

package chremoas_roles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MemberListList struct {
	MemberLists []*MemberList `protobuf:"bytes,1,rep,name=MemberLists" json:"MemberLists,omitempty"`
}

func (m *MemberListList) Reset()                    { *m = MemberListList{} }
func (m *MemberListList) String() string            { return proto.CompactTextString(m) }
func (*MemberListList) ProtoMessage()               {}
func (*MemberListList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MemberListList) GetMemberLists() []*MemberList {
	if m != nil {
		return m.MemberLists
	}
	return nil
}

type MemberList struct {
	Name        string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
}

func (m *MemberList) Reset()                    { *m = MemberList{} }
func (m *MemberList) String() string            { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()               {}
func (*MemberList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *MemberList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberList) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MemberInfo struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	List string `protobuf:"bytes,2,opt,name=List" json:"List,omitempty"`
}

func (m *MemberInfo) Reset()                    { *m = MemberInfo{} }
func (m *MemberInfo) String() string            { return proto.CompactTextString(m) }
func (*MemberInfo) ProtoMessage()               {}
func (*MemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *MemberInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberInfo) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

type MemberInfoList struct {
	Members []*MemberInfo `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
}

func (m *MemberInfoList) Reset()                    { *m = MemberInfoList{} }
func (m *MemberInfoList) String() string            { return proto.CompactTextString(m) }
func (*MemberInfoList) ProtoMessage()               {}
func (*MemberInfoList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MemberInfoList) GetMembers() []*MemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*MemberListList)(nil), "chremoas.roles.MemberListList")
	proto.RegisterType((*MemberList)(nil), "chremoas.roles.MemberList")
	proto.RegisterType((*MemberInfo)(nil), "chremoas.roles.MemberInfo")
	proto.RegisterType((*MemberInfoList)(nil), "chremoas.roles.MemberInfoList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MemberLists service

type MemberListsClient interface {
	GetLists(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*MemberListList, error)
	AddList(ctx context.Context, in *MemberList, opts ...client.CallOption) (*NilMessage, error)
	RemoveList(ctx context.Context, in *MemberList, opts ...client.CallOption) (*NilMessage, error)
	GetMembers(ctx context.Context, in *MemberList, opts ...client.CallOption) (*MemberInfoList, error)
	AddMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error)
	RemoveMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error)
}

type memberListsClient struct {
	c           client.Client
	serviceName string
}

func NewMemberListsClient(serviceName string, c client.Client) MemberListsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.roles"
	}
	return &memberListsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *memberListsClient) GetLists(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*MemberListList, error) {
	req := c.c.NewRequest(c.serviceName, "MemberLists.GetLists", in)
	out := new(MemberListList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberListsClient) AddList(ctx context.Context, in *MemberList, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "MemberLists.AddList", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberListsClient) RemoveList(ctx context.Context, in *MemberList, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "MemberLists.RemoveList", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberListsClient) GetMembers(ctx context.Context, in *MemberList, opts ...client.CallOption) (*MemberInfoList, error) {
	req := c.c.NewRequest(c.serviceName, "MemberLists.GetMembers", in)
	out := new(MemberInfoList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberListsClient) AddMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "MemberLists.AddMember", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberListsClient) RemoveMember(ctx context.Context, in *MemberInfo, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "MemberLists.RemoveMember", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemberLists service

type MemberListsHandler interface {
	GetLists(context.Context, *NilMessage, *MemberListList) error
	AddList(context.Context, *MemberList, *NilMessage) error
	RemoveList(context.Context, *MemberList, *NilMessage) error
	GetMembers(context.Context, *MemberList, *MemberInfoList) error
	AddMember(context.Context, *MemberInfo, *NilMessage) error
	RemoveMember(context.Context, *MemberInfo, *NilMessage) error
}

func RegisterMemberListsHandler(s server.Server, hdlr MemberListsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MemberLists{hdlr}, opts...))
}

type MemberLists struct {
	MemberListsHandler
}

func (h *MemberLists) GetLists(ctx context.Context, in *NilMessage, out *MemberListList) error {
	return h.MemberListsHandler.GetLists(ctx, in, out)
}

func (h *MemberLists) AddList(ctx context.Context, in *MemberList, out *NilMessage) error {
	return h.MemberListsHandler.AddList(ctx, in, out)
}

func (h *MemberLists) RemoveList(ctx context.Context, in *MemberList, out *NilMessage) error {
	return h.MemberListsHandler.RemoveList(ctx, in, out)
}

func (h *MemberLists) GetMembers(ctx context.Context, in *MemberList, out *MemberInfoList) error {
	return h.MemberListsHandler.GetMembers(ctx, in, out)
}

func (h *MemberLists) AddMember(ctx context.Context, in *MemberInfo, out *NilMessage) error {
	return h.MemberListsHandler.AddMember(ctx, in, out)
}

func (h *MemberLists) RemoveMember(ctx context.Context, in *MemberInfo, out *NilMessage) error {
	return h.MemberListsHandler.RemoveMember(ctx, in, out)
}

func init() { proto.RegisterFile("memberLists.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6e, 0x82, 0x40,
	0x10, 0xc6, 0xa5, 0x9a, 0x5a, 0x07, 0x63, 0xd2, 0x39, 0x11, 0x0e, 0x86, 0xec, 0xc9, 0x13, 0x07,
	0xeb, 0xb1, 0x17, 0xfb, 0x47, 0x6d, 0x53, 0x39, 0xf0, 0x06, 0x08, 0xd3, 0x96, 0xc4, 0x65, 0xcd,
	0xee, 0xa6, 0xef, 0xd7, 0x37, 0x6b, 0xd8, 0x85, 0xa2, 0x69, 0xc5, 0x03, 0x07, 0x92, 0x61, 0x76,
	0xbe, 0xdf, 0xce, 0xf7, 0x65, 0xe1, 0x96, 0x13, 0xdf, 0x91, 0x7c, 0xcb, 0x95, 0x56, 0xe1, 0x41,
	0x0a, 0x2d, 0x70, 0x92, 0x7e, 0x4a, 0xe2, 0x22, 0x51, 0xa1, 0x14, 0x7b, 0x52, 0xfe, 0x38, 0x15,
	0x9c, 0x8b, 0xc2, 0x9e, 0xb2, 0x08, 0x26, 0xdb, 0x5f, 0x49, 0xf9, 0xe1, 0x3d, 0xb8, 0x4d, 0x47,
	0x79, 0x4e, 0xd0, 0x9f, 0xb9, 0x73, 0x3f, 0x3c, 0xa5, 0x84, 0xcd, 0x48, 0x7c, 0x3c, 0xce, 0x1e,
	0x00, 0x9a, 0x5f, 0x44, 0x18, 0x44, 0x09, 0x27, 0xcf, 0x09, 0x9c, 0xd9, 0x28, 0x36, 0x35, 0x06,
	0xe0, 0x3e, 0x91, 0x4a, 0x65, 0x7e, 0xd0, 0xb9, 0x28, 0xbc, 0x2b, 0x73, 0x74, 0xdc, 0x62, 0x8b,
	0x9a, 0xf1, 0x52, 0xbc, 0x8b, 0x7f, 0x19, 0x08, 0x83, 0x92, 0x5f, 0x89, 0x4d, 0xcd, 0x56, 0xb5,
	0x93, 0x52, 0x65, 0x6e, 0x5f, 0xc0, 0xd0, 0x76, 0x2e, 0xb8, 0x28, 0x05, 0x71, 0x3d, 0x3a, 0xff,
	0xee, 0x9f, 0x04, 0x80, 0x1b, 0xb8, 0x59, 0x93, 0xb6, 0xf5, 0x1f, 0x40, 0x94, 0xef, 0xb7, 0xa4,
	0x54, 0xf2, 0x41, 0xfe, 0xf4, 0x7c, 0x44, 0x66, 0xbf, 0x1e, 0x3e, 0xc2, 0x70, 0x99, 0x65, 0x66,
	0xb5, 0x96, 0x3c, 0xfd, 0x96, 0x4b, 0x58, 0x0f, 0x57, 0x00, 0x31, 0x71, 0xf1, 0x45, 0x1d, 0x39,
	0xaf, 0x00, 0x6b, 0xd2, 0x95, 0xe9, 0x56, 0xce, 0xf4, 0x7c, 0x6a, 0x95, 0xb1, 0x67, 0x18, 0x2d,
	0xb3, 0xcc, 0xb6, 0xb1, 0x25, 0xe4, 0x0b, 0x2b, 0x6d, 0x60, 0x6c, 0xad, 0x75, 0x25, 0xed, 0xae,
	0xcd, 0xe3, 0xbe, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x61, 0xb2, 0xec, 0xac, 0x0f, 0x03, 0x00,
	0x00,
}
