// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permissions.proto

/*
Package chremoas_permissions is a generated protocol buffer package.

It is generated from these files:
	permissions.proto

It has these top-level messages:
	PermissionsRequest
	PermissionsResponse
	PerformResponse
*/
package chremoas_permissions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdminRoles int32

const (
	AdminRoles_SERVER_ADMIN  AdminRoles = 0
	AdminRoles_ROLE_ADMIN    AdminRoles = 1
	AdminRoles_SIG_ADMIN     AdminRoles = 2
	AdminRoles_CHANNEL_ADMIN AdminRoles = 3
)

var AdminRoles_name = map[int32]string{
	0: "SERVER_ADMIN",
	1: "ROLE_ADMIN",
	2: "SIG_ADMIN",
	3: "CHANNEL_ADMIN",
}
var AdminRoles_value = map[string]int32{
	"SERVER_ADMIN":  0,
	"ROLE_ADMIN":    1,
	"SIG_ADMIN":     2,
	"CHANNEL_ADMIN": 3,
}

func (x AdminRoles) String() string {
	return proto.EnumName(AdminRoles_name, int32(x))
}
func (AdminRoles) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PermissionsRequest struct {
	User            string       `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	PermissionsList []AdminRoles `protobuf:"varint,2,rep,packed,name=PermissionsList,enum=chremoas.permissions.AdminRoles" json:"PermissionsList,omitempty"`
}

func (m *PermissionsRequest) Reset()                    { *m = PermissionsRequest{} }
func (m *PermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*PermissionsRequest) ProtoMessage()               {}
func (*PermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PermissionsRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PermissionsRequest) GetPermissionsList() []AdminRoles {
	if m != nil {
		return m.PermissionsList
	}
	return nil
}

type PermissionsResponse struct {
	PermissionsList []AdminRoles `protobuf:"varint,1,rep,packed,name=PermissionsList,enum=chremoas.permissions.AdminRoles" json:"PermissionsList,omitempty"`
}

func (m *PermissionsResponse) Reset()                    { *m = PermissionsResponse{} }
func (m *PermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*PermissionsResponse) ProtoMessage()               {}
func (*PermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PermissionsResponse) GetPermissionsList() []AdminRoles {
	if m != nil {
		return m.PermissionsList
	}
	return nil
}

type PerformResponse struct {
	CanPerform bool `protobuf:"varint,1,opt,name=CanPerform" json:"CanPerform,omitempty"`
}

func (m *PerformResponse) Reset()                    { *m = PerformResponse{} }
func (m *PerformResponse) String() string            { return proto.CompactTextString(m) }
func (*PerformResponse) ProtoMessage()               {}
func (*PerformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PerformResponse) GetCanPerform() bool {
	if m != nil {
		return m.CanPerform
	}
	return false
}

func init() {
	proto.RegisterType((*PermissionsRequest)(nil), "chremoas.permissions.PermissionsRequest")
	proto.RegisterType((*PermissionsResponse)(nil), "chremoas.permissions.PermissionsResponse")
	proto.RegisterType((*PerformResponse)(nil), "chremoas.permissions.PerformResponse")
	proto.RegisterEnum("chremoas.permissions.AdminRoles", AdminRoles_name, AdminRoles_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Permissions service

type PermissionsClient interface {
	Perform(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PerformResponse, error)
	AddPermisssions(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PermissionsResponse, error)
	RemovePermissions(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PermissionsResponse, error)
	GetPermissions(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PermissionsResponse, error)
}

type permissionsClient struct {
	c           client.Client
	serviceName string
}

func NewPermissionsClient(serviceName string, c client.Client) PermissionsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.permissions"
	}
	return &permissionsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *permissionsClient) Perform(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PerformResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Permissions.Perform", in)
	out := new(PerformResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) AddPermisssions(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PermissionsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Permissions.AddPermisssions", in)
	out := new(PermissionsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) RemovePermissions(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PermissionsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Permissions.RemovePermissions", in)
	out := new(PermissionsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetPermissions(ctx context.Context, in *PermissionsRequest, opts ...client.CallOption) (*PermissionsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Permissions.GetPermissions", in)
	out := new(PermissionsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Permissions service

type PermissionsHandler interface {
	Perform(context.Context, *PermissionsRequest, *PerformResponse) error
	AddPermisssions(context.Context, *PermissionsRequest, *PermissionsResponse) error
	RemovePermissions(context.Context, *PermissionsRequest, *PermissionsResponse) error
	GetPermissions(context.Context, *PermissionsRequest, *PermissionsResponse) error
}

func RegisterPermissionsHandler(s server.Server, hdlr PermissionsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Permissions{hdlr}, opts...))
}

type Permissions struct {
	PermissionsHandler
}

func (h *Permissions) Perform(ctx context.Context, in *PermissionsRequest, out *PerformResponse) error {
	return h.PermissionsHandler.Perform(ctx, in, out)
}

func (h *Permissions) AddPermisssions(ctx context.Context, in *PermissionsRequest, out *PermissionsResponse) error {
	return h.PermissionsHandler.AddPermisssions(ctx, in, out)
}

func (h *Permissions) RemovePermissions(ctx context.Context, in *PermissionsRequest, out *PermissionsResponse) error {
	return h.PermissionsHandler.RemovePermissions(ctx, in, out)
}

func (h *Permissions) GetPermissions(ctx context.Context, in *PermissionsRequest, out *PermissionsResponse) error {
	return h.PermissionsHandler.GetPermissions(ctx, in, out)
}

func init() { proto.RegisterFile("permissions.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xd7, 0xf5, 0xcf, 0x5f, 0x77, 0x75, 0xdd, 0x7a, 0xf5, 0x61, 0xf8, 0x20, 0xa5, 0x20,
	0x54, 0x1f, 0x0a, 0xce, 0x4f, 0x50, 0x66, 0x99, 0x93, 0x5a, 0x47, 0x86, 0x3e, 0x09, 0x52, 0x6d,
	0x74, 0x15, 0xdb, 0xd4, 0xde, 0xe8, 0x87, 0xf2, 0x53, 0x0a, 0x35, 0x6c, 0x51, 0x2b, 0x0c, 0x61,
	0x6f, 0xb9, 0x27, 0x27, 0xe7, 0x97, 0x43, 0x08, 0xd8, 0x25, 0xaf, 0xf2, 0x8c, 0x28, 0x13, 0x05,
	0xf9, 0x65, 0x25, 0xa4, 0xc0, 0xdd, 0xfb, 0x79, 0xc5, 0x73, 0x91, 0x90, 0xaf, 0xed, 0xb9, 0x12,
	0x70, 0xba, 0x1c, 0x19, 0x7f, 0x79, 0xe5, 0x24, 0x11, 0xe1, 0xdf, 0x15, 0xf1, 0x6a, 0x60, 0x38,
	0x86, 0xd7, 0x61, 0xf5, 0x1a, 0xcf, 0xa1, 0xa7, 0x39, 0xa3, 0x8c, 0xe4, 0xa0, 0xed, 0x98, 0x9e,
	0x35, 0x74, 0xfc, 0xa6, 0x64, 0x3f, 0x48, 0xf3, 0xac, 0x60, 0xe2, 0x99, 0x13, 0xfb, 0x7e, 0xd0,
	0x4d, 0x60, 0xe7, 0x0b, 0x95, 0x4a, 0x51, 0x10, 0x6f, 0x42, 0x18, 0x7f, 0x45, 0x1c, 0xd7, 0x59,
	0x0f, 0xa2, 0xca, 0x17, 0xf1, 0xfb, 0x00, 0xa3, 0xa4, 0x50, 0x6a, 0xdd, 0x6d, 0x93, 0x69, 0xca,
	0xd1, 0x14, 0x60, 0x99, 0x88, 0x7d, 0xd8, 0x9e, 0x85, 0xec, 0x3a, 0x64, 0xb7, 0xc1, 0xe9, 0xc5,
	0x24, 0xee, 0xb7, 0xd0, 0x02, 0x60, 0x97, 0x51, 0xa8, 0x66, 0x03, 0xbb, 0xd0, 0x99, 0x4d, 0xc6,
	0x6a, 0x6c, 0xa3, 0x0d, 0xdd, 0xd1, 0x59, 0x10, 0xc7, 0x61, 0xa4, 0x24, 0x73, 0xf8, 0x6e, 0xc2,
	0x96, 0x76, 0x31, 0xbc, 0x81, 0x0d, 0x05, 0x43, 0xaf, 0xb9, 0xd2, 0xcf, 0xc7, 0xd8, 0x3b, 0xf8,
	0xd5, 0xa9, 0xb7, 0x73, 0x5b, 0x38, 0x87, 0x5e, 0x90, 0xa6, 0x2a, 0xe1, 0x13, 0xb8, 0x3a, 0xe5,
	0x70, 0x05, 0xe7, 0x82, 0xf4, 0x04, 0x36, 0xe3, 0xb9, 0x78, 0xe3, 0x7a, 0xb9, 0x35, 0xb1, 0x1e,
	0xc1, 0x1a, 0x73, 0xb9, 0x7e, 0xd0, 0xdd, 0xff, 0xfa, 0x9f, 0x9c, 0x7c, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x74, 0x29, 0xed, 0x86, 0x3c, 0x03, 0x00, 0x00,
}
