// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roles.proto

package chremoas_roles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MemberSyncAction int32

const (
	MemberSyncAction_NOTHING MemberSyncAction = 0
	MemberSyncAction_ADDED   MemberSyncAction = 1
	MemberSyncAction_REMOVED MemberSyncAction = 2
)

var MemberSyncAction_name = map[int32]string{
	0: "NOTHING",
	1: "ADDED",
	2: "REMOVED",
}
var MemberSyncAction_value = map[string]int32{
	"NOTHING": 0,
	"ADDED":   1,
	"REMOVED": 2,
}

func (x MemberSyncAction) String() string {
	return proto.EnumName(MemberSyncAction_name, int32(x))
}
func (MemberSyncAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type StringList struct {
	Value []string `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty"`
}

func (m *StringList) Reset()                    { *m = StringList{} }
func (m *StringList) String() string            { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()               {}
func (*StringList) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *StringList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Role struct {
	Type      string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	ShortName string `protobuf:"bytes,2,opt,name=ShortName" json:"ShortName,omitempty"`
	FilterA   string `protobuf:"bytes,3,opt,name=FilterA" json:"FilterA,omitempty"`
	FilterB   string `protobuf:"bytes,4,opt,name=FilterB" json:"FilterB,omitempty"`
	// Discord
	Name        string `protobuf:"bytes,5,opt,name=Name" json:"Name,omitempty"`
	Color       int32  `protobuf:"varint,6,opt,name=Color" json:"Color,omitempty"`
	Hoist       bool   `protobuf:"varint,7,opt,name=Hoist" json:"Hoist,omitempty"`
	Position    int32  `protobuf:"varint,8,opt,name=Position" json:"Position,omitempty"`
	Permissions int32  `protobuf:"varint,9,opt,name=Permissions" json:"Permissions,omitempty"`
	Managed     bool   `protobuf:"varint,10,opt,name=Managed" json:"Managed,omitempty"`
	Mentionable bool   `protobuf:"varint,11,opt,name=Mentionable" json:"Mentionable,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Role) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Role) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Role) GetFilterA() string {
	if m != nil {
		return m.FilterA
	}
	return ""
}

func (m *Role) GetFilterB() string {
	if m != nil {
		return m.FilterB
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Role) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *Role) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Role) GetPermissions() int32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *Role) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

func (m *Role) GetMentionable() bool {
	if m != nil {
		return m.Mentionable
	}
	return false
}

type UpdateInfo struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=Value" json:"Value,omitempty"`
}

func (m *UpdateInfo) Reset()                    { *m = UpdateInfo{} }
func (m *UpdateInfo) String() string            { return proto.CompactTextString(m) }
func (*UpdateInfo) ProtoMessage()               {}
func (*UpdateInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *UpdateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetRolesResponse struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *GetRolesResponse) Reset()                    { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()               {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleSyncResponse struct {
	Added   []string `protobuf:"bytes,1,rep,name=Added" json:"Added,omitempty"`
	Removed []string `protobuf:"bytes,2,rep,name=Removed" json:"Removed,omitempty"`
}

func (m *RoleSyncResponse) Reset()                    { *m = RoleSyncResponse{} }
func (m *RoleSyncResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleSyncResponse) ProtoMessage()               {}
func (*RoleSyncResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *RoleSyncResponse) GetAdded() []string {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *RoleSyncResponse) GetRemoved() []string {
	if m != nil {
		return m.Removed
	}
	return nil
}

type MemberSyncResult struct {
	Action MemberSyncAction `protobuf:"varint,1,opt,name=Action,enum=chremoas.roles.MemberSyncAction" json:"Action,omitempty"`
	User   string           `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
	Role   string           `protobuf:"bytes,3,opt,name=Role" json:"Role,omitempty"`
}

func (m *MemberSyncResult) Reset()                    { *m = MemberSyncResult{} }
func (m *MemberSyncResult) String() string            { return proto.CompactTextString(m) }
func (*MemberSyncResult) ProtoMessage()               {}
func (*MemberSyncResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *MemberSyncResult) GetAction() MemberSyncAction {
	if m != nil {
		return m.Action
	}
	return MemberSyncAction_NOTHING
}

func (m *MemberSyncResult) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MemberSyncResult) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type MemberSyncResponse struct {
	Results []*MemberSyncResult `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
}

func (m *MemberSyncResponse) Reset()                    { *m = MemberSyncResponse{} }
func (m *MemberSyncResponse) String() string            { return proto.CompactTextString(m) }
func (*MemberSyncResponse) ProtoMessage()               {}
func (*MemberSyncResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *MemberSyncResponse) GetResults() []*MemberSyncResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*StringList)(nil), "chremoas.roles.StringList")
	proto.RegisterType((*Role)(nil), "chremoas.roles.Role")
	proto.RegisterType((*UpdateInfo)(nil), "chremoas.roles.UpdateInfo")
	proto.RegisterType((*GetRolesResponse)(nil), "chremoas.roles.GetRolesResponse")
	proto.RegisterType((*RoleSyncResponse)(nil), "chremoas.roles.RoleSyncResponse")
	proto.RegisterType((*MemberSyncResult)(nil), "chremoas.roles.MemberSyncResult")
	proto.RegisterType((*MemberSyncResponse)(nil), "chremoas.roles.MemberSyncResponse")
	proto.RegisterEnum("chremoas.roles.MemberSyncAction", MemberSyncAction_name, MemberSyncAction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Roles service

type RolesClient interface {
	AddRole(ctx context.Context, in *Role, opts ...client.CallOption) (*NilMessage, error)
	UpdateRole(ctx context.Context, in *UpdateInfo, opts ...client.CallOption) (*NilMessage, error)
	RemoveRole(ctx context.Context, in *Role, opts ...client.CallOption) (*NilMessage, error)
	GetRoles(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*GetRolesResponse, error)
	GetRole(ctx context.Context, in *Role, opts ...client.CallOption) (*Role, error)
	SyncRoles(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*RoleSyncResponse, error)
	GetRoleKeys(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*StringList, error)
	GetRoleTypes(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*StringList, error)
	SyncMembers(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*MemberSyncResponse, error)
}

type rolesClient struct {
	c           client.Client
	serviceName string
}

func NewRolesClient(serviceName string, c client.Client) RolesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.roles"
	}
	return &rolesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *rolesClient) AddRole(ctx context.Context, in *Role, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.AddRole", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) UpdateRole(ctx context.Context, in *UpdateInfo, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.UpdateRole", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) RemoveRole(ctx context.Context, in *Role, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.RemoveRole", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetRoles(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*GetRolesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.GetRoles", in)
	out := new(GetRolesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetRole(ctx context.Context, in *Role, opts ...client.CallOption) (*Role, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.GetRole", in)
	out := new(Role)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) SyncRoles(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*RoleSyncResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.SyncRoles", in)
	out := new(RoleSyncResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetRoleKeys(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*StringList, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.GetRoleKeys", in)
	out := new(StringList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetRoleTypes(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*StringList, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.GetRoleTypes", in)
	out := new(StringList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) SyncMembers(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*MemberSyncResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Roles.SyncMembers", in)
	out := new(MemberSyncResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Roles service

type RolesHandler interface {
	AddRole(context.Context, *Role, *NilMessage) error
	UpdateRole(context.Context, *UpdateInfo, *NilMessage) error
	RemoveRole(context.Context, *Role, *NilMessage) error
	GetRoles(context.Context, *NilMessage, *GetRolesResponse) error
	GetRole(context.Context, *Role, *Role) error
	SyncRoles(context.Context, *NilMessage, *RoleSyncResponse) error
	GetRoleKeys(context.Context, *NilMessage, *StringList) error
	GetRoleTypes(context.Context, *NilMessage, *StringList) error
	SyncMembers(context.Context, *NilMessage, *MemberSyncResponse) error
}

func RegisterRolesHandler(s server.Server, hdlr RolesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Roles{hdlr}, opts...))
}

type Roles struct {
	RolesHandler
}

func (h *Roles) AddRole(ctx context.Context, in *Role, out *NilMessage) error {
	return h.RolesHandler.AddRole(ctx, in, out)
}

func (h *Roles) UpdateRole(ctx context.Context, in *UpdateInfo, out *NilMessage) error {
	return h.RolesHandler.UpdateRole(ctx, in, out)
}

func (h *Roles) RemoveRole(ctx context.Context, in *Role, out *NilMessage) error {
	return h.RolesHandler.RemoveRole(ctx, in, out)
}

func (h *Roles) GetRoles(ctx context.Context, in *NilMessage, out *GetRolesResponse) error {
	return h.RolesHandler.GetRoles(ctx, in, out)
}

func (h *Roles) GetRole(ctx context.Context, in *Role, out *Role) error {
	return h.RolesHandler.GetRole(ctx, in, out)
}

func (h *Roles) SyncRoles(ctx context.Context, in *NilMessage, out *RoleSyncResponse) error {
	return h.RolesHandler.SyncRoles(ctx, in, out)
}

func (h *Roles) GetRoleKeys(ctx context.Context, in *NilMessage, out *StringList) error {
	return h.RolesHandler.GetRoleKeys(ctx, in, out)
}

func (h *Roles) GetRoleTypes(ctx context.Context, in *NilMessage, out *StringList) error {
	return h.RolesHandler.GetRoleTypes(ctx, in, out)
}

func (h *Roles) SyncMembers(ctx context.Context, in *NilMessage, out *MemberSyncResponse) error {
	return h.RolesHandler.SyncMembers(ctx, in, out)
}

func init() { proto.RegisterFile("roles.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xb5, 0x49, 0x1c, 0xf0, 0x38, 0x8a, 0xac, 0x15, 0x87, 0x15, 0xea, 0x01, 0xed, 0x09, 0xe5,
	0xc0, 0x21, 0x3d, 0xa4, 0xaa, 0xd4, 0xaa, 0xa4, 0x24, 0x21, 0xa5, 0x7c, 0xc8, 0x24, 0xb9, 0x1b,
	0x3c, 0x25, 0x96, 0x6c, 0x2f, 0xf2, 0x3a, 0x95, 0xf8, 0x03, 0xfd, 0x29, 0xfd, 0x9d, 0xd5, 0x7e,
	0x18, 0x13, 0x48, 0xa9, 0xda, 0xde, 0x76, 0xde, 0xcc, 0xbe, 0x7d, 0xf3, 0x66, 0x6c, 0xf0, 0x72,
	0x9e, 0xa0, 0xe8, 0xae, 0x72, 0x5e, 0x70, 0x72, 0xb6, 0x78, 0xca, 0x31, 0xe5, 0xa1, 0xe8, 0x2a,
	0xb4, 0x75, 0xba, 0xe0, 0x69, 0xca, 0x33, 0x9d, 0x65, 0x0c, 0x60, 0x56, 0xe4, 0x71, 0xb6, 0xfc,
	0x1a, 0x8b, 0x82, 0x34, 0xc1, 0x79, 0x0c, 0x93, 0x67, 0xa4, 0x76, 0xfb, 0xa8, 0xe3, 0x06, 0x3a,
	0x60, 0x3f, 0x6b, 0x70, 0x1c, 0xf0, 0x04, 0x09, 0x81, 0xe3, 0xfb, 0xf5, 0x4a, 0x66, 0xed, 0x8e,
	0x1b, 0xa8, 0x33, 0x79, 0x03, 0xee, 0xec, 0x89, 0xe7, 0xc5, 0x38, 0x4c, 0x91, 0xd6, 0x54, 0xa2,
	0x02, 0x08, 0x85, 0xfa, 0x4d, 0x9c, 0x14, 0x98, 0xf7, 0xe8, 0x91, 0xca, 0x95, 0x61, 0x95, 0xb9,
	0xa2, 0xc7, 0xdb, 0x99, 0x2b, 0xf9, 0x8a, 0x22, 0x73, 0xf4, 0x2b, 0x8a, 0xa7, 0x09, 0xce, 0x67,
	0x9e, 0xf0, 0x9c, 0x9e, 0xb4, 0xed, 0x8e, 0x13, 0xe8, 0x40, 0xa2, 0x03, 0x1e, 0x8b, 0x82, 0xd6,
	0xdb, 0x76, 0xa7, 0x11, 0xe8, 0x80, 0xb4, 0xa0, 0x31, 0xe5, 0x22, 0x2e, 0x62, 0x9e, 0xd1, 0x86,
	0x2a, 0xdf, 0xc4, 0xa4, 0x0d, 0xde, 0x14, 0xf3, 0x34, 0x16, 0x22, 0xe6, 0x99, 0xa0, 0xae, 0x4a,
	0x6f, 0x43, 0x52, 0xd7, 0x28, 0xcc, 0xc2, 0x25, 0x46, 0x14, 0x14, 0x6b, 0x19, 0xca, 0xbb, 0x23,
	0xcc, 0x24, 0x4d, 0x38, 0x4f, 0x90, 0x7a, 0x2a, 0xbb, 0x0d, 0xb1, 0x01, 0xc0, 0xc3, 0x2a, 0x0a,
	0x0b, 0xbc, 0xcb, 0xbe, 0xf1, 0x4d, 0x1f, 0xf6, 0x56, 0x1f, 0x3e, 0x1c, 0x0d, 0x71, 0x6d, 0x7c,
	0x92, 0xc7, 0xca, 0x72, 0xed, 0x8f, 0xb1, 0xfc, 0x23, 0xf8, 0xb7, 0x58, 0x48, 0xd3, 0x45, 0x80,
	0x62, 0xc5, 0x33, 0x81, 0xe4, 0x1c, 0x1c, 0x05, 0xa8, 0xe1, 0x78, 0x17, 0xcd, 0xee, 0xcb, 0xc1,
	0x76, 0x65, 0x32, 0xd0, 0x25, 0xec, 0x0a, 0x7c, 0x79, 0x98, 0xad, 0xb3, 0xc5, 0xe6, 0x7e, 0x13,
	0x9c, 0x5e, 0x14, 0x61, 0x54, 0x0e, 0x57, 0x05, 0xb2, 0xdf, 0x00, 0x53, 0xfe, 0x1d, 0x23, 0x5a,
	0x53, 0x78, 0x19, 0xb2, 0x02, 0xfc, 0x11, 0xa6, 0x73, 0xcc, 0x0d, 0xcb, 0x73, 0x52, 0x90, 0x77,
	0x70, 0xd2, 0x5b, 0x28, 0x67, 0x65, 0x57, 0x67, 0x17, 0xed, 0x5d, 0x11, 0xd5, 0x0d, 0x5d, 0x17,
	0x98, 0x7a, 0xe9, 0xc6, 0x83, 0xc0, 0xdc, 0xb4, 0xae, 0xce, 0x12, 0x93, 0x2a, 0x4d, 0xeb, 0xea,
	0xcc, 0xa6, 0x40, 0x5e, 0xbc, 0xaa, 0xb5, 0xbf, 0x97, 0x2a, 0xa5, 0x82, 0xb2, 0xfb, 0x03, 0x0f,
	0xeb, 0xc2, 0xa0, 0xbc, 0x70, 0x7e, 0xb9, 0xdd, 0x87, 0x51, 0xe3, 0x41, 0x7d, 0x3c, 0xb9, 0x1f,
	0xdc, 0x8d, 0x6f, 0x7d, 0x8b, 0xb8, 0xe0, 0xf4, 0xfa, 0xfd, 0xeb, 0xbe, 0x6f, 0x4b, 0x3c, 0xb8,
	0x1e, 0x4d, 0x1e, 0xaf, 0xfb, 0x7e, 0xed, 0xe2, 0x87, 0x63, 0x1c, 0x27, 0x1f, 0xa0, 0xde, 0x8b,
	0x22, 0xf5, 0x0d, 0xbc, 0x6a, 0x7b, 0xab, 0xb5, 0x8b, 0x8e, 0xe3, 0x64, 0x84, 0x42, 0x84, 0x4b,
	0x64, 0x16, 0xb9, 0x29, 0xf7, 0x42, 0x31, 0xec, 0xd5, 0x56, 0x3b, 0xf3, 0x07, 0x9e, 0x4f, 0x00,
	0x7a, 0x38, 0xff, 0xac, 0xe4, 0x0b, 0x34, 0xca, 0xbd, 0x22, 0x07, 0x2a, 0x5b, 0x7b, 0xf6, 0xee,
	0x6e, 0x23, 0xb3, 0xc8, 0x25, 0xd4, 0x0d, 0xfa, 0x1b, 0x29, 0xaf, 0xa2, 0xcc, 0x22, 0x43, 0x70,
	0xd5, 0x9c, 0xfe, 0x5e, 0xc5, 0xee, 0x4e, 0x33, 0x8b, 0xdc, 0x82, 0x67, 0x54, 0x0c, 0x71, 0x7d,
	0x98, 0x6e, 0x2f, 0x57, 0xfd, 0xf9, 0x98, 0x45, 0x06, 0x70, 0x6a, 0x88, 0xe4, 0x7f, 0xed, 0x7f,
	0x98, 0x26, 0xe0, 0x49, 0x91, 0x7a, 0xe9, 0x0e, 0x13, 0xb1, 0x83, 0x6b, 0x6c, 0x7a, 0x9c, 0x9f,
	0xa8, 0x7f, 0xf5, 0xdb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x09, 0x9f, 0x07, 0xd8, 0x05,
	0x00, 0x00,
}
