// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roles.proto

/*
Package chremoas_roles is a generated protocol buffer package.

It is generated from these files:
	roles.proto

It has these top-level messages:
	NilMessage
	StringList
	Role
	UpdateInfo
	GetRolesResponse
	RoleSyncResponse
	FilterList
	Filter
	Members
	MemberList
*/
package chremoas_roles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NilMessage struct {
}

func (m *NilMessage) Reset()                    { *m = NilMessage{} }
func (m *NilMessage) String() string            { return proto.CompactTextString(m) }
func (*NilMessage) ProtoMessage()               {}
func (*NilMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StringList struct {
	Value []string `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty"`
}

func (m *StringList) Reset()                    { *m = StringList{} }
func (m *StringList) String() string            { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()               {}
func (*StringList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StringList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Role struct {
	Type      string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	ShortName string `protobuf:"bytes,2,opt,name=ShortName" json:"ShortName,omitempty"`
	FilterA   string `protobuf:"bytes,3,opt,name=FilterA" json:"FilterA,omitempty"`
	FilterB   string `protobuf:"bytes,4,opt,name=FilterB" json:"FilterB,omitempty"`
	Sig       bool   `protobuf:"varint,5,opt,name=Sig" json:"Sig,omitempty"`
	Joinable  bool   `protobuf:"varint,6,opt,name=Joinable" json:"Joinable,omitempty"`
	// Discord
	Name        string `protobuf:"bytes,20,opt,name=Name" json:"Name,omitempty"`
	Color       int32  `protobuf:"varint,21,opt,name=Color" json:"Color,omitempty"`
	Hoist       bool   `protobuf:"varint,22,opt,name=Hoist" json:"Hoist,omitempty"`
	Position    int32  `protobuf:"varint,23,opt,name=Position" json:"Position,omitempty"`
	Permissions int32  `protobuf:"varint,24,opt,name=Permissions" json:"Permissions,omitempty"`
	Managed     bool   `protobuf:"varint,25,opt,name=Managed" json:"Managed,omitempty"`
	Mentionable bool   `protobuf:"varint,26,opt,name=Mentionable" json:"Mentionable,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Role) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Role) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Role) GetFilterA() string {
	if m != nil {
		return m.FilterA
	}
	return ""
}

func (m *Role) GetFilterB() string {
	if m != nil {
		return m.FilterB
	}
	return ""
}

func (m *Role) GetSig() bool {
	if m != nil {
		return m.Sig
	}
	return false
}

func (m *Role) GetJoinable() bool {
	if m != nil {
		return m.Joinable
	}
	return false
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Role) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *Role) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Role) GetPermissions() int32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *Role) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

func (m *Role) GetMentionable() bool {
	if m != nil {
		return m.Mentionable
	}
	return false
}

type UpdateInfo struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=Value" json:"Value,omitempty"`
}

func (m *UpdateInfo) Reset()                    { *m = UpdateInfo{} }
func (m *UpdateInfo) String() string            { return proto.CompactTextString(m) }
func (*UpdateInfo) ProtoMessage()               {}
func (*UpdateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetRolesResponse struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *GetRolesResponse) Reset()                    { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()               {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleSyncResponse struct {
	Added   []string `protobuf:"bytes,1,rep,name=Added" json:"Added,omitempty"`
	Removed []string `protobuf:"bytes,2,rep,name=Removed" json:"Removed,omitempty"`
}

func (m *RoleSyncResponse) Reset()                    { *m = RoleSyncResponse{} }
func (m *RoleSyncResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleSyncResponse) ProtoMessage()               {}
func (*RoleSyncResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RoleSyncResponse) GetAdded() []string {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *RoleSyncResponse) GetRemoved() []string {
	if m != nil {
		return m.Removed
	}
	return nil
}

type FilterList struct {
	FilterList []*Filter `protobuf:"bytes,1,rep,name=FilterList" json:"FilterList,omitempty"`
}

func (m *FilterList) Reset()                    { *m = FilterList{} }
func (m *FilterList) String() string            { return proto.CompactTextString(m) }
func (*FilterList) ProtoMessage()               {}
func (*FilterList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FilterList) GetFilterList() []*Filter {
	if m != nil {
		return m.FilterList
	}
	return nil
}

type Filter struct {
	Name        string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Filter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Members struct {
	Name   []string `protobuf:"bytes,1,rep,name=Name" json:"Name,omitempty"`
	Filter string   `protobuf:"bytes,2,opt,name=Filter" json:"Filter,omitempty"`
}

func (m *Members) Reset()                    { *m = Members{} }
func (m *Members) String() string            { return proto.CompactTextString(m) }
func (*Members) ProtoMessage()               {}
func (*Members) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Members) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Members) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type MemberList struct {
	Members []string `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
}

func (m *MemberList) Reset()                    { *m = MemberList{} }
func (m *MemberList) String() string            { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()               {}
func (*MemberList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MemberList) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*NilMessage)(nil), "chremoas.roles.NilMessage")
	proto.RegisterType((*StringList)(nil), "chremoas.roles.StringList")
	proto.RegisterType((*Role)(nil), "chremoas.roles.Role")
	proto.RegisterType((*UpdateInfo)(nil), "chremoas.roles.UpdateInfo")
	proto.RegisterType((*GetRolesResponse)(nil), "chremoas.roles.GetRolesResponse")
	proto.RegisterType((*RoleSyncResponse)(nil), "chremoas.roles.RoleSyncResponse")
	proto.RegisterType((*FilterList)(nil), "chremoas.roles.FilterList")
	proto.RegisterType((*Filter)(nil), "chremoas.roles.Filter")
	proto.RegisterType((*Members)(nil), "chremoas.roles.Members")
	proto.RegisterType((*MemberList)(nil), "chremoas.roles.MemberList")
}

func init() { proto.RegisterFile("roles.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x6f, 0x13, 0x3f,
	0x10, 0xdd, 0x34, 0x4d, 0x93, 0x4c, 0xfa, 0xfb, 0x29, 0xb2, 0x42, 0x6b, 0x22, 0x0e, 0x91, 0x0f,
	0x28, 0xe2, 0x90, 0x43, 0x11, 0x70, 0xa2, 0x22, 0x69, 0xd5, 0x94, 0x96, 0x54, 0xd5, 0x06, 0xb8,
	0x6f, 0xeb, 0x21, 0xb5, 0xb4, 0x59, 0x47, 0xeb, 0x05, 0x29, 0xdf, 0x86, 0x0f, 0xc5, 0x07, 0x42,
	0x1e, 0xef, 0x3f, 0xb6, 0x69, 0x4b, 0xe9, 0xcd, 0x6f, 0x66, 0xfc, 0xf2, 0x3c, 0xf3, 0x66, 0x03,
	0x9d, 0x58, 0x87, 0x68, 0x46, 0xab, 0x58, 0x27, 0x9a, 0xfd, 0x7f, 0x7d, 0x13, 0xe3, 0x52, 0x07,
	0x66, 0x44, 0x51, 0xb1, 0x0b, 0x70, 0xa1, 0xc2, 0x19, 0x1a, 0x13, 0x2c, 0x50, 0x08, 0x80, 0x79,
	0x12, 0xab, 0x68, 0xf1, 0x49, 0x99, 0x84, 0xf5, 0xa0, 0xf1, 0x35, 0x08, 0xbf, 0x23, 0xaf, 0x0d,
	0xea, 0xc3, 0xb6, 0xef, 0x80, 0xf8, 0xb5, 0x05, 0xdb, 0xbe, 0x0e, 0x91, 0x31, 0xd8, 0xfe, 0xbc,
	0x5e, 0xd9, 0x6c, 0x6d, 0xd8, 0xf6, 0xe9, 0xcc, 0x5e, 0x40, 0x7b, 0x7e, 0xa3, 0xe3, 0xe4, 0x22,
	0x58, 0x22, 0xdf, 0xa2, 0x44, 0x11, 0x60, 0x1c, 0x9a, 0x27, 0x2a, 0x4c, 0x30, 0x1e, 0xf3, 0x3a,
	0xe5, 0x32, 0x58, 0x64, 0x26, 0x7c, 0xbb, 0x9c, 0x99, 0xb0, 0x2e, 0xd4, 0xe7, 0x6a, 0xc1, 0x1b,
	0x83, 0xda, 0xb0, 0xe5, 0xdb, 0x23, 0xeb, 0x43, 0xeb, 0x4c, 0xab, 0x28, 0xb8, 0x0a, 0x91, 0xef,
	0x50, 0x38, 0xc7, 0x56, 0x13, 0xfd, 0x74, 0xcf, 0x69, 0xa2, 0x5f, 0xed, 0x41, 0xe3, 0x48, 0x87,
	0x3a, 0xe6, 0xcf, 0x06, 0xb5, 0x61, 0xc3, 0x77, 0xc0, 0x46, 0x4f, 0xb5, 0x32, 0x09, 0xdf, 0x23,
	0x0a, 0x07, 0x2c, 0xf7, 0xa5, 0x36, 0x2a, 0x51, 0x3a, 0xe2, 0xfb, 0x54, 0x9e, 0x63, 0x36, 0x80,
	0xce, 0x25, 0xc6, 0x4b, 0x65, 0x8c, 0xd2, 0x91, 0xe1, 0x9c, 0xd2, 0xe5, 0x90, 0x7d, 0xc5, 0x2c,
	0x88, 0x82, 0x05, 0x4a, 0xfe, 0x9c, 0x58, 0x33, 0x68, 0xef, 0xce, 0x30, 0xb2, 0x34, 0x24, 0xbb,
	0x4f, 0xd9, 0x72, 0x48, 0x9c, 0x02, 0x7c, 0x59, 0xc9, 0x20, 0xc1, 0x8f, 0xd1, 0x37, 0x9d, 0xbf,
	0xa3, 0x56, 0x7a, 0x47, 0x17, 0xea, 0xe7, 0xb8, 0x4e, 0xbb, 0x6a, 0x8f, 0xc5, 0x80, 0x5c, 0x37,
	0xd3, 0x01, 0x1d, 0x42, 0x77, 0x8a, 0x89, 0x1d, 0x91, 0xf1, 0xd1, 0xac, 0x74, 0x64, 0x90, 0xbd,
	0x82, 0x06, 0x05, 0x68, 0x94, 0x9d, 0x83, 0xde, 0xe8, 0x4f, 0x1b, 0x8c, 0x6c, 0xd2, 0x77, 0x25,
	0x62, 0x02, 0x5d, 0x7b, 0x98, 0xaf, 0xa3, 0xeb, 0xfc, 0x7e, 0x0f, 0x1a, 0x63, 0x29, 0x51, 0x66,
	0x56, 0x20, 0x60, 0xdf, 0xeb, 0xe3, 0x52, 0xff, 0x40, 0xc9, 0xb7, 0x28, 0x9e, 0x41, 0x71, 0x0c,
	0xe0, 0x06, 0x48, 0x46, 0x7a, 0x5b, 0x46, 0xa9, 0x84, 0xbd, 0xaa, 0x04, 0x57, 0xe1, 0x97, 0x2a,
	0xc5, 0x21, 0xec, 0x38, 0xb4, 0xb1, 0x1f, 0x03, 0xe8, 0x1c, 0xa3, 0xb9, 0x8e, 0xd5, 0x8a, 0xc6,
	0xe5, 0xfa, 0x52, 0x0e, 0x89, 0x37, 0xd0, 0x9c, 0xe1, 0xf2, 0x0a, 0x63, 0x53, 0x22, 0xa8, 0xe7,
	0x04, 0x7b, 0x19, 0x7d, 0x7a, 0x37, 0x45, 0xe2, 0x25, 0x80, 0xbb, 0x46, 0xe2, 0x79, 0x4e, 0x92,
	0x5e, 0xce, 0xe0, 0xc1, 0xcf, 0x56, 0xda, 0x55, 0xf6, 0x1e, 0x9a, 0x63, 0x29, 0x69, 0x2b, 0x36,
	0xb6, 0xb6, 0xdf, 0xaf, 0x46, 0x4b, 0x4b, 0xe7, 0xb1, 0x93, 0x6c, 0xf6, 0xc4, 0x70, 0xab, 0xb6,
	0xf0, 0xc5, 0x03, 0x3c, 0x1f, 0x00, 0xdc, 0x00, 0xfe, 0x59, 0xc9, 0x19, 0xb4, 0x32, 0xef, 0xb0,
	0x7b, 0x2a, 0xfb, 0x83, 0x6a, 0xae, 0xea, 0x38, 0xe1, 0xb1, 0x77, 0xd0, 0x4c, 0xa3, 0x77, 0x48,
	0xd9, 0x18, 0x15, 0x1e, 0x3b, 0x87, 0x36, 0x99, 0xef, 0xf1, 0x2a, 0xaa, 0xbe, 0x15, 0x1e, 0x9b,
	0x42, 0x27, 0x55, 0x71, 0x8e, 0xeb, 0xfb, 0xe9, 0x6e, 0xe5, 0x8a, 0x6f, 0xa1, 0xf0, 0xd8, 0x29,
	0xec, 0xa6, 0x44, 0xf6, 0x4b, 0xf7, 0x14, 0xa6, 0x29, 0x74, 0xac, 0xc8, 0xcc, 0x9a, 0x8f, 0x22,
	0xaa, 0xfa, 0x66, 0x8a, 0x89, 0x73, 0xed, 0x23, 0x79, 0x4a, 0x5b, 0xe6, 0xb1, 0x31, 0xb4, 0xc7,
	0x52, 0xa6, 0xab, 0x76, 0xc7, 0x62, 0x3e, 0x20, 0xe5, 0x18, 0x76, 0x9d, 0xf5, 0x9e, 0xc4, 0x32,
	0xa1, 0x07, 0x65, 0x8d, 0xf9, 0x6b, 0x8e, 0x62, 0x5b, 0x85, 0xc7, 0x8e, 0x00, 0xc6, 0x52, 0x66,
	0x1c, 0xfb, 0x9b, 0x6b, 0xcd, 0x83, 0x9d, 0xfd, 0xcf, 0x3d, 0xe7, 0x69, 0x3c, 0x57, 0x3b, 0xf4,
	0xaf, 0xfb, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xb0, 0x48, 0x4b, 0x84, 0x07, 0x00,
	0x00,
}
