// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rules.proto

package chremoas_roles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Rule struct {
	Name string    `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Rule *RuleInfo `protobuf:"bytes,2,opt,name=Rule" json:"Rule,omitempty"`
}

func (m *Rule) Reset()                    { *m = Rule{} }
func (m *Rule) String() string            { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()               {}
func (*Rule) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rule) GetRule() *RuleInfo {
	if m != nil {
		return m.Rule
	}
	return nil
}

type RuleInfo struct {
	Role    string `protobuf:"bytes,1,opt,name=Role" json:"Role,omitempty"`
	FilterA string `protobuf:"bytes,2,opt,name=FilterA" json:"FilterA,omitempty"`
	FilterB string `protobuf:"bytes,3,opt,name=FilterB" json:"FilterB,omitempty"`
}

func (m *RuleInfo) Reset()                    { *m = RuleInfo{} }
func (m *RuleInfo) String() string            { return proto.CompactTextString(m) }
func (*RuleInfo) ProtoMessage()               {}
func (*RuleInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *RuleInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RuleInfo) GetFilterA() string {
	if m != nil {
		return m.FilterA
	}
	return ""
}

func (m *RuleInfo) GetFilterB() string {
	if m != nil {
		return m.FilterB
	}
	return ""
}

type RulesList struct {
	Rules []*Rule `protobuf:"bytes,1,rep,name=Rules" json:"Rules,omitempty"`
}

func (m *RulesList) Reset()                    { *m = RulesList{} }
func (m *RulesList) String() string            { return proto.CompactTextString(m) }
func (*RulesList) ProtoMessage()               {}
func (*RulesList) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *RulesList) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*Rule)(nil), "chremoas.roles.Rule")
	proto.RegisterType((*RuleInfo)(nil), "chremoas.roles.RuleInfo")
	proto.RegisterType((*RulesList)(nil), "chremoas.roles.RulesList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Rules service

type RulesClient interface {
	AddRule(ctx context.Context, in *Rule, opts ...client.CallOption) (*NilMessage, error)
	RemoveRule(ctx context.Context, in *Rule, opts ...client.CallOption) (*NilMessage, error)
	GetRules(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*RulesList, error)
	GetRule(ctx context.Context, in *Rule, opts ...client.CallOption) (*Rule, error)
}

type rulesClient struct {
	c           client.Client
	serviceName string
}

func NewRulesClient(serviceName string, c client.Client) RulesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.roles"
	}
	return &rulesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *rulesClient) AddRule(ctx context.Context, in *Rule, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Rules.AddRule", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rulesClient) RemoveRule(ctx context.Context, in *Rule, opts ...client.CallOption) (*NilMessage, error) {
	req := c.c.NewRequest(c.serviceName, "Rules.RemoveRule", in)
	out := new(NilMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rulesClient) GetRules(ctx context.Context, in *NilMessage, opts ...client.CallOption) (*RulesList, error) {
	req := c.c.NewRequest(c.serviceName, "Rules.GetRules", in)
	out := new(RulesList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rulesClient) GetRule(ctx context.Context, in *Rule, opts ...client.CallOption) (*Rule, error) {
	req := c.c.NewRequest(c.serviceName, "Rules.GetRule", in)
	out := new(Rule)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rules service

type RulesHandler interface {
	AddRule(context.Context, *Rule, *NilMessage) error
	RemoveRule(context.Context, *Rule, *NilMessage) error
	GetRules(context.Context, *NilMessage, *RulesList) error
	GetRule(context.Context, *Rule, *Rule) error
}

func RegisterRulesHandler(s server.Server, hdlr RulesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Rules{hdlr}, opts...))
}

type Rules struct {
	RulesHandler
}

func (h *Rules) AddRule(ctx context.Context, in *Rule, out *NilMessage) error {
	return h.RulesHandler.AddRule(ctx, in, out)
}

func (h *Rules) RemoveRule(ctx context.Context, in *Rule, out *NilMessage) error {
	return h.RulesHandler.RemoveRule(ctx, in, out)
}

func (h *Rules) GetRules(ctx context.Context, in *NilMessage, out *RulesList) error {
	return h.RulesHandler.GetRules(ctx, in, out)
}

func (h *Rules) GetRule(ctx context.Context, in *Rule, out *Rule) error {
	return h.RulesHandler.GetRule(ctx, in, out)
}

func init() { proto.RegisterFile("rules.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x93, 0xb6, 0x90, 0xe6, 0x82, 0x18, 0x4e, 0x0c, 0x26, 0x53, 0xe4, 0x29, 0x42, 0x28,
	0x43, 0x18, 0x3a, 0x21, 0xd1, 0x22, 0xf1, 0x47, 0x82, 0x0e, 0xfe, 0x06, 0xa1, 0x3d, 0x20, 0x92,
	0xdd, 0x43, 0x76, 0xca, 0x47, 0xe0, 0x73, 0xa3, 0x38, 0x0d, 0xff, 0x14, 0x18, 0xd8, 0xee, 0xde,
	0x7b, 0xfe, 0xe9, 0x9d, 0x0c, 0x89, 0xdd, 0x6a, 0x72, 0xc5, 0x8b, 0xe5, 0x86, 0xf1, 0x70, 0xf5,
	0x6c, 0xc9, 0x70, 0xe5, 0x0a, 0xcb, 0x9a, 0x5c, 0x7a, 0xb0, 0x62, 0x63, 0x78, 0xd3, 0xb9, 0xf2,
	0x06, 0x26, 0x6a, 0xab, 0x09, 0x11, 0x26, 0xcb, 0xca, 0x90, 0x08, 0xb3, 0x30, 0x8f, 0x95, 0x9f,
	0xf1, 0xb4, 0xf3, 0xc4, 0x28, 0x0b, 0xf3, 0xa4, 0x14, 0xc5, 0x77, 0x50, 0xd1, 0x7a, 0xb7, 0x9b,
	0x47, 0x56, 0x3e, 0x25, 0x15, 0x4c, 0x7b, 0xa5, 0xa5, 0x29, 0xd6, 0x1f, 0xb4, 0x76, 0x46, 0x01,
	0xd1, 0x55, 0xad, 0x1b, 0xb2, 0x73, 0x0f, 0x8c, 0x55, 0xbf, 0x7e, 0x3a, 0x0b, 0x31, 0xfe, 0xea,
	0x2c, 0xe4, 0x0c, 0xe2, 0x96, 0xe9, 0xee, 0x6a, 0xd7, 0xe0, 0x09, 0xec, 0xf9, 0x45, 0x84, 0xd9,
	0x38, 0x4f, 0xca, 0xa3, 0xa1, 0x3e, 0xaa, 0x8b, 0x94, 0x6f, 0xa3, 0x5d, 0x18, 0xcf, 0x21, 0x9a,
	0xaf, 0xd7, 0xfe, 0xc6, 0xc1, 0x17, 0x69, 0xfa, 0x53, 0x5d, 0xd6, 0xfa, 0x9e, 0x9c, 0xab, 0x9e,
	0x48, 0x06, 0x78, 0x01, 0xa0, 0xc8, 0xf0, 0x2b, 0xfd, 0x9b, 0x70, 0x09, 0xd3, 0x6b, 0x6a, 0xba,
	0x32, 0x7f, 0x24, 0xd3, 0xe3, 0x21, 0xb6, 0xbf, 0x5c, 0x06, 0x38, 0x83, 0x68, 0x07, 0xf9, 0xa5,
	0xc3, 0xa0, 0x2a, 0x83, 0x87, 0x7d, 0xff, 0xcd, 0x67, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0xb2, 0x53, 0x3e, 0x13, 0x02, 0x00, 0x00,
}
